# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: ap-southeast-2

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 4
